"use client";

import Link from "next/link";
import { useState, type CSSProperties } from "react";
import { Search, Clock } from "lucide-react";
import type { FrontEndThemeContext } from "@/lib/site-theme";
import { formatDate, localizePath, t } from "@/components/site/utils";
import { SocialLinks } from "@/components/site/social-links";

type CssVars = CSSProperties;

const RULES: Record<string, string> = {
  double: "4px double var(--theme-header-border)",
  solid: "1px solid var(--theme-header-border)",
  none: "none",
};

/** Colours come from the --theme-* variables generated by buildThemeCss, never from literals. */
export function SiteHeader({ theme }: { theme: FrontEndThemeContext }) {
  const mods = theme.mods || {};
  const [activeHoverIdx, setActiveHoverIdx] = useState<number | null>(null);

  const headerLayout = mods.headerLayout || theme.headerLayout || "classic";
  const borderBottom = RULES[mods.headerBorderStyle || "double"] ?? RULES.double;
  const homeHref = localizePath("/", theme.locale, theme.defaultLocale);

  const headerStyle: CssVars = {
    backgroundColor: "var(--theme-header-bg)",
    color: "var(--theme-header-text)",
    borderBottom,
  };
  const navStyle: CssVars = {
    backgroundColor: "var(--theme-nav-bg)",
    color: "var(--theme-nav-link)",
    borderTop: "1px solid var(--theme-header-border)",
  };
  const titleStyle = (fallbackWeight: string): CssVars => ({
    color: "var(--theme-header-text)",
    textTransform: mods.headingTransform || "none",
    fontWeight: mods.headingFontWeight || fallbackWeight,
  });
  const taglineStyle: CssVars = { color: "var(--theme-muted)" };
  const stickyClass = mods.stickyHeader ? "sticky top-0 z-40" : "";

  const renderLogo = (fallbackWidth: number, className = "") =>
    mods.logoUrl ? (
      <img
        src={mods.logoUrl}
        alt="Logo"
        style={{ width: `${mods.logoWidth || fallbackWidth}px` }}
        className={className}
      />
    ) : null;

  const showSocialsInNav = mods.showTopBar === false && mods.showSocialIconsInHeader !== false;

  // Search icon (and social icons when there is no top bar to host them).
  const renderSearchIcon = () =>
    (mods.showSearchInNav !== false || showSocialsInNav) && (
      <div className="ps-4 hidden sm:flex items-center gap-3 opacity-80">
        {showSocialsInNav && <SocialLinks mods={mods} />}
        {mods.showSearchInNav !== false && <Search className="size-3.5" />}
      </div>
    );
  // Top Bar Ticker & Utility
  const renderTopBar = () => {
    if (mods.showTopBar === false) return null;

    const showTicker = theme.activePlugins?.includes("breaking-news");

    return (
      <div
        style={{ backgroundColor: "var(--theme-topbar-bg)", color: "var(--theme-topbar-text)" }}
        className="px-4 sm:px-6 py-1.5 text-xs border-b border-black/10"
      >
        <div className="mx-auto flex theme-container items-center justify-between">
          {showTicker ? (
            <div className="flex items-center gap-2 overflow-hidden text-ellipsis whitespace-nowrap">
              <span
                style={{
                  backgroundColor: "var(--theme-topbar-ticker-bg)",
                  color: "var(--theme-topbar-ticker-text)",
                }}
                className="rounded px-1.5 py-0.5 text-[0.625rem] font-bold uppercase tracking-wider animate-pulse flex-shrink-0"
              >
                {t("site.breaking", theme, "Breaking")}
              </span>
              <span className="text-xs font-medium truncate max-w-xl">
                {mods.topBarTickerText
                  ? theme.dict?.[mods.topBarTickerText] || mods.topBarTickerText
                  : t("site.ticker_default", theme, "Editorial dispatch: Global supply chains adjust to new infrastructure corridors")}
              </span>
            </div>
          ) : (
            <span />
          )}
          <div className="flex items-center gap-3">
            {mods.showSocialIconsInHeader !== false && <SocialLinks mods={mods} />}
            {mods.showDateInHeader !== false && (
              <span className="text-[0.6875rem] opacity-75 font-mono hidden sm:inline flex-shrink-0">
                {formatDate(new Date(), theme.locale)}
              </span>
            )}
            {theme.languages && theme.languages.length > 1 && (
              <div className="flex items-center gap-1.5 text-[0.6875rem] font-medium border-s border-current/20 ps-3">
                {theme.languages.map((lang, idx) => (
                  <span key={lang.code} className="inline-flex items-center gap-1.5">
                    {idx > 0 && <span className="opacity-40">|</span>}
                    <Link
                      href={lang.url}
                      className={`hover:underline transition-opacity ${
                        lang.isActive ? "font-bold underline" : "opacity-80 hover:opacity-100"
                      }`}
                      title={lang.name}
                    >
                      {lang.nativeName || lang.name}
                    </Link>
                  </span>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    );
  };

  // Nav Items
  const renderNavLinks = () => {
    const justify =
      mods.navAlignment === "center"
        ? "justify-center"
        : mods.navAlignment === "right"
          ? "justify-end"
          : mods.navAlignment === "between"
            ? "justify-between"
            : "justify-start";
    const isPill = mods.navStyle === "pill-badge";
    const isUnderlined = mods.navStyle === "underlined";

    return (
      <div className={`flex items-center gap-1.5 sm:gap-2 flex-wrap ${justify}`}>
        {theme.primaryNav.map((item, idx) => {
          const isHovered = activeHoverIdx === idx;
          const isActive = idx === 0;

          const style: CssVars = { color: "var(--theme-nav-link)" };
          if (isPill) {
            if (isActive) {
              style.backgroundColor = "var(--theme-primary)";
              style.color = "var(--theme-on-primary)";
            } else {
              style.backgroundColor = `color-mix(in srgb, var(--theme-nav-link) ${isHovered ? 22 : 12}%, transparent)`;
              if (isHovered) style.color = "var(--theme-nav-link-hover)";
            }
          } else if (isActive || isHovered) {
            style.color = "var(--theme-nav-link-hover)";
          }
          if (isUnderlined && isActive) style.borderColor = "var(--theme-nav-link-hover)";
          style.textTransform = mods.navUppercase ? "uppercase" : "none";

          return (
            <Link
              key={item.id}
              href={item.url}
              onMouseEnter={() => setActiveHoverIdx(idx)}
              onMouseLeave={() => setActiveHoverIdx(null)}
              style={style}
              className={`theme-nav-link font-bold tracking-wider transition-all duration-150 whitespace-nowrap ${
                isPill
                  ? "px-3 py-1 rounded-md shadow-xs"
                  : isUnderlined && isActive
                    ? "border-b-2 pb-0.5"
                    : "hover:opacity-85"
              }`}
            >
              {item.title}
            </Link>
          );
        })}
      </div>
    );
  };

  // 1. MINIMAL LAYOUT
  if (headerLayout === "minimal") {
    return (
      <header style={headerStyle} className={`transition-colors backdrop-blur-sm z-40 ${stickyClass}`}>
        {renderTopBar()}
        <div className="mx-auto flex theme-container items-center justify-between px-6 py-4">
          <div className="flex items-center gap-3">
            {renderLogo(140) ||
              (mods.showSiteTitle !== false && (
                <div>
                  <Link href={homeHref} style={titleStyle("700")} className="theme-site-title text-2xl font-bold tracking-tight">
                    {theme.siteTitle}
                  </Link>
                  {mods.showTagline !== false && (
                    <p style={taglineStyle} className="text-[0.625rem] uppercase tracking-widest">
                      {theme.siteTagline}
                    </p>
                  )}
                </div>
              ))}
          </div>

          <nav className="hidden items-center gap-6 text-sm font-medium md:flex">{renderNavLinks()}</nav>

          <div className="flex items-center gap-3">
            {showSocialsInNav && <SocialLinks mods={mods} className="hidden sm:flex" />}
            {mods.showSearchInNav !== false && (
              <button type="button" aria-label="Search" className="p-1.5 opacity-60 hover:opacity-100">
                <Search className="size-4" />
              </button>
            )}
            <Link
              href={localizePath("/about", theme.locale, theme.defaultLocale)}
              style={{ borderColor: "var(--theme-primary)", color: "var(--theme-primary)" }}
              className="rounded-full border px-4 py-1.5 text-xs font-semibold hover:opacity-80 transition-opacity"
            >
              {t("site.about", theme, "About")}
            </Link>
          </div>
        </div>
      </header>
    );
  }

  // 2. MAGAZINE MULTI-TIER LAYOUT
  if (headerLayout === "magazine") {
    return (
      <header style={headerStyle} className={`transition-colors ${stickyClass}`}>
        {renderTopBar()}

        <div className="mx-auto flex theme-container items-center justify-between px-6 py-6">
          <div>
            {renderLogo(200) ||
              (mods.showSiteTitle !== false && (
                <div>
                  <Link
                    href={homeHref}
                    style={titleStyle("900")}
                    className="theme-site-title text-3xl sm:text-5xl font-black uppercase tracking-tighter"
                  >
                    {theme.siteTitle}
                  </Link>
                  {mods.showTagline !== false && (
                    <p style={taglineStyle} className="text-xs font-medium uppercase tracking-widest mt-0.5">
                      {theme.siteTagline}
                    </p>
                  )}
                </div>
              ))}
          </div>

          <div className="hidden lg:flex items-center gap-3">
            <span
              style={{ backgroundColor: "var(--theme-surface)", color: "var(--theme-text)", borderColor: "var(--theme-border)" }}
              className="rounded-lg border px-3 py-1 text-xs font-medium flex items-center gap-1.5"
            >
              <Clock className="size-3" style={{ color: "var(--theme-primary)" }} />
              {t("site.live_newsroom_edition", theme, "Live Newsroom Edition")}
            </span>
          </div>
        </div>

        <div style={navStyle}>
          <div className="mx-auto flex theme-container items-center justify-between px-6 py-3">
            {renderNavLinks()}
            {renderSearchIcon()}
          </div>
        </div>
      </header>
    );
  }

  // 3. CENTERED EDITORIAL LAYOUT
  if (headerLayout === "centered") {
    return (
      <header style={headerStyle} className={`transition-colors ${stickyClass}`}>
        {renderTopBar()}

        <div className="mx-auto theme-container px-6 py-8 text-center space-y-2">
          {renderLogo(180, "mx-auto") ||
            (mods.showSiteTitle !== false && (
              <Link
                href={homeHref}
                style={titleStyle("700")}
                className="theme-site-title text-4xl sm:text-5xl font-bold tracking-tight inline-block"
              >
                {theme.siteTitle}
              </Link>
            ))}
          {mods.showTagline !== false && (
            <p style={taglineStyle} className="text-xs font-mono tracking-widest uppercase">
              {theme.siteTagline}
            </p>
          )}
        </div>

        <nav style={navStyle} className="px-6 py-2.5">
          <div className="mx-auto theme-container flex items-center justify-center">{renderNavLinks()}</div>
        </nav>
      </header>
    );
  }

  // 4. CLASSIC BROADSHEET NEWSPAPER MASTHEAD (Default)
  return (
    <header style={headerStyle} className={`transition-colors ${stickyClass}`}>
      {renderTopBar()}

      {mods.showDateInHeader !== false && (
        <div
          style={{ borderColor: "var(--theme-header-border)", color: "var(--theme-muted)" }}
          className="border-b px-6 py-1.5 text-[0.6875rem] uppercase tracking-widest"
        >
          <div className="mx-auto theme-container flex items-center justify-between">
            <span>{t("site.daily_record", theme, "The Daily Record")}</span>
            <span>{formatDate(new Date(), theme.locale)}</span>
            <span>{t("site.independent_bureau", theme, "Independent Bureau")}</span>
          </div>
        </div>
      )}

      <div className="mx-auto theme-container px-6 py-8 text-center">
        {renderLogo(200, "mx-auto") ||
          (mods.showSiteTitle !== false && (
            <Link href={homeHref} style={titleStyle("900")} className="theme-site-title text-4xl sm:text-6xl font-black tracking-tight block">
              {theme.siteTitle}
            </Link>
          ))}
        {mods.showTagline !== false && (
          <p style={taglineStyle} className="mt-2 text-xs font-serif italic">
            {theme.siteTagline}
          </p>
        )}
      </div>

      <nav style={navStyle} className="px-6 py-2.5">
        <div className="mx-auto theme-container flex items-center justify-between">
          {renderNavLinks()}
          {renderSearchIcon()}
        </div>
      </nav>
    </header>
  );
}
